{{- if not .Values.peertube.admin.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: peertube-admin-secret
data:
  {{- if not .Values.peertube.admin.existingSecretKeys.email }}
  username: {{ .Values.peertube.admin.username }}
  {{- end }}
  {{- if not .Values.peertube.admin.existingSecretKeys.password }}
  password: {{ .Values.peertube.admin.password }}
  {{- end }}
{{- end }}
