{{- if not .Values.externalDatabase.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: peertube-db
data:
  {{- if not .Values.externalDatabase.existingSecretKeys.hostname }}
  hostname: {{ .Values.externalDatabase.hostname }}
  {{- end }}
  {{- if not .Values.externalDatabase.existingSecretKeys.database }}
  database: {{ .Values.externalDatabase.database }}
  {{- end }}
  {{- if not .Values.externalDatabase.existingSecretKeys.username }}
  username: {{ .Values.externalDatabase.username }}
  {{- end }}
  {{- if not .Values.externalDatabase.existingSecretKeys.password }}
  password: {{ .Values.externalDatabase.password }}
  {{- end }}
{{- end }}
