{{- if not .Values.peertube.smtp.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: peertube-smtp
data:
  host: {{ .Values.peertube.smtp.host }}
  username: {{ .Values.peertube.smtp.username }}
  password: {{ .Values.peertube.smtp.password }}
{{- end }}
