{{- if and (not .Values.peertube.s3.existingSecret) .Values.peertube.s3.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: peertube-s3
data:
  access_key_id: {{ .Values.peertube.s3.access_key_id }}
  secret_access_key: {{ .Values.peertube.s3.secret_access_key }}
{{- end }}
